### ISSUE TITLE
[Bug] 페이징 length 고정

### ISSUE THREAD

**Issue by Huijiny** [mash-up-kr/ssam-d-Android#224]
## 발생 중인 현상

- 페이징 불러왔던게 또불러오는 경우도 있는듯 -> 일단 pageLength 10으로 고정

## 관련 링크

-

**Comment by Huijiny** [comment]
서버이슈

**Comment by sooziini** [comment]
서버는 고쳐졌으나..
1) pageLength 15 -> 5 -> 5 ..로 불러올 시 total page 변경되어 list 이상하게 불러와지는 이슈 발생
item 17개일 때
첫 번째: pageLength 15 pageNo 1 total 2
- list: {0 ~14}
두 번째: pageLength 5 pageNo 2 total 4
- list: {5 ~ 9}
세 번째: pageLength 5 pageNo 3 total 4
- list: {10 ~ 14}
네 번째: pageLength 5 pageNo 4 total 4
- list: {15 ~ 16}

2) pageLength 10으로 고정 시 pageNo 1&2 같이 불러와지는 이슈 발생
