### ISSUE TITLE
자동화 구성 (CI)

### ISSUE THREAD

**Issue by JaesungLeee** [mash-up-kr/ssam-d-Android#3]
## 설명

- Github Actions로 CI 구성
- codeowners

## 관련 링크

- https://sungbin.land/github-actions-%EC%9C%BC%EB%A1%9C-%EC%95%88%EB%93%9C%EB%A1%9C%EC%9D%B4%EB%93%9C-ci-cd-%EA%B5%AC%EC%B6%95%ED%95%98%EA%B8%B0-1aaaa6595c4a
- https://sungbin.land/ktlint-detekt-%EC%9C%BC%EB%A1%9C-%EC%BD%94%EB%93%9C-%ED%80%84%EB%A6%AC%ED%8B%B0-%ED%96%A5%EC%83%81%EC%8B%9C%ED%82%A4%EA%B8%B0-a085c7eba2cd
- https://studynote.oopy.io/kotlin/2

**Comment by sooziini** [comment]
전에 내가 말했던 convention 맞춰서 자동으로 고쳐주는 건데 spotless 함 참고하면 좋을 거 같애 ㅎㅅㅎ
- https://decisive-cough-37e.notion.site/CI-b6867032967b422e9d805adfb1ad723e
- https://parkwow.medium.com/lint-spotless-c05bf67618e0
