### ISSUE TITLE
[Bug] windowSoftInputMode API 버전 대응

### ISSUE THREAD

**Issue by JaesungLeee** [mash-up-kr/ssam-d-Android#67]
## 발생 중인 현상

- 특정 버전 이하부터는 adjustResize가 적용되지 않는 현상

| 버전 | 발생 현상 |
|--------|--------|
| API 33 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/b30e1be6-9fba-47d4-a95f-d67688680b04" width=300 /> |
| API 28 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/ab1924bc-affe-488f-b614-1a2391190247" width=300 />  | 

## 관련 링크

- https://stickode.tistory.com/591
- https://developer.android.com/training/keyboard-input/visibility?hl=ko

**Comment by Huijiny** [comment]
논이슈입니다
