### ISSUE TITLE
Composable 스크린 Column에서 Scaffold로 리팩터링

### ISSUE THREAD

**Issue by JaesungLeee** [mash-up-kr/ssam-d-Android#87]
## 설명

- 기존 루트 컴포저블 Column으로 구현된 스크린을 Scaffold로 변경하는 작업

## 관련 링크

- none

**Comment by Huijiny** [comment]
온보딩 완료
홈, 가이드 화면은 scaffold로 하면 투명 툴바가 불가능해서 패스

**Comment by sooziini** [comment]
LoginScreen은 적용되어 있음

**Comment by Huijiny** [comment]
새로운 것들은 만들면서 Scaffold로 적용했을테니 닫습니다.
